/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_connexion (void)
{
  GtkWidget *connexion;
  GtkWidget *fixed1;
  GtkWidget *entry2;   /* username */
  GtkWidget *entry3;   /* password */
  GtkWidget *label2;
  GtkWidget *label1;
  GtkWidget *image1;
  GtkWidget *button1;
  GtkWidget *label3;
  GtkWidget *image34;

  connexion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (connexion), _("connexion"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (connexion), fixed1);

  /* -------- username -------- */
  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 136, 64);
  gtk_widget_set_size_request (entry2, 120, 32);
  gtk_entry_set_text (GTK_ENTRY (entry2), _("Ex:Ahmed"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  /* -------- password -------- */
  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed1), entry3, 136, 168);
  gtk_widget_set_size_request (entry3, 120, 32);
  gtk_entry_set_text (GTK_ENTRY (entry3), _("Ex:1256"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label2 = gtk_label_new (_("password:"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 160, 136);
  gtk_widget_set_size_request (label2, 72, 24);

  label1 = gtk_label_new (_("username:"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 152, 32);
  gtk_widget_set_size_request (label1, 88, 32);

  image1 = create_pixmap (connexion, "Capture d'écran 2025-10-11 012224.png");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 264, 0);
  gtk_widget_set_size_request (image1, 448, 656);
  gtk_misc_set_padding (GTK_MISC (image1), 0, 2);

  button1 = gtk_button_new_with_mnemonic (_("Login"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 160, 440);
  gtk_widget_set_size_request (button1, 64, 32);

  label3 = gtk_label_new (_("\tIncorrect password"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 112, 480);
  gtk_widget_set_size_request (label3, 168, 24);

  image34 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_fixed_put (GTK_FIXED (fixed1), image34, 232, 448);
  gtk_widget_set_size_request (image34, 21, 21);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (connexion, connexion, "connexion");
  GLADE_HOOKUP_OBJECT (connexion, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (connexion, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (connexion, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (connexion, label2, "label2");
  GLADE_HOOKUP_OBJECT (connexion, label1, "label1");
  GLADE_HOOKUP_OBJECT (connexion, image1, "image1");
  GLADE_HOOKUP_OBJECT (connexion, button1, "button1");
  GLADE_HOOKUP_OBJECT (connexion, label3, "label3");
  GLADE_HOOKUP_OBJECT (connexion, image34, "image34");

  return connexion;
}



GtkWidget*
create_Espace_Admin (void)
{
  GtkWidget *Espace_Admin;
  GtkWidget *fixed2;
  GtkWidget *fixed3;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton3;
  GtkWidget *radiobutton4;

  Espace_Admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Espace_Admin), _("Espace Admin"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Espace_Admin), fixed2);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_fixed_put (GTK_FIXED (fixed2), fixed3, 272, 96);
  gtk_widget_set_size_request (fixed3, 50, 50);

  label9 = gtk_label_new (_("Member Managment"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 104, 80);
  gtk_widget_set_size_request (label9, 184, 24);

  label10 = gtk_label_new (_("Coach managment"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 96, 128);
  gtk_widget_set_size_request (label10, 184, 24);

  label11 = gtk_label_new (_("Course Managment"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 96, 168);
  gtk_widget_set_size_request (label11, 184, 24);

  label12 = gtk_label_new (_("Equipment Managment"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 112, 208);
  gtk_widget_set_size_request (label12, 184, 24);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton1, 328, 88);
  gtk_widget_set_size_request (radiobutton1, 56, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton2, 328, 128);
  gtk_widget_set_size_request (radiobutton2, 40, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton3, 328, 168);
  gtk_widget_set_size_request (radiobutton3, 40, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton4, 328, 208);
  gtk_widget_set_size_request (radiobutton4, 32, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Espace_Admin, Espace_Admin, "Espace_Admin");
  GLADE_HOOKUP_OBJECT (Espace_Admin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Espace_Admin, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Espace_Admin, label9, "label9");
  GLADE_HOOKUP_OBJECT (Espace_Admin, label10, "label10");
  GLADE_HOOKUP_OBJECT (Espace_Admin, label11, "label11");
  GLADE_HOOKUP_OBJECT (Espace_Admin, label12, "label12");
  GLADE_HOOKUP_OBJECT (Espace_Admin, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (Espace_Admin, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (Espace_Admin, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (Espace_Admin, radiobutton4, "radiobutton4");

  return Espace_Admin;
}

GtkWidget*
create_Espace_Coach (void)
{
  GtkWidget *Espace_Coach;
  GtkWidget *fixed4;
  GtkWidget *textview1;
  GtkWidget *comboboxentry14;
  GtkWidget *calendar4;
  GtkWidget *Gym_registration;
  GtkWidget *center;
  GtkWidget *Register;
  GtkWidget *Start_date;
  GtkWidget *button8;
  GtkWidget *button9;

  Espace_Coach = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Espace_Coach), _("Espace Coach"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Espace_Coach), fixed4);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_fixed_put (GTK_FIXED (fixed4), textview1, 456, 160);
  gtk_widget_set_size_request (textview1, 144, 80);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview1)), _("Upcoming Courses \n- Yoga: 10 AM \n- CrossFit : 2 PM"), -1);

  comboboxentry14 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry14);
  gtk_fixed_put (GTK_FIXED (fixed4), comboboxentry14, 160, 40);
  gtk_widget_set_size_request (comboboxentry14, 189, 29);

  calendar4 = gtk_calendar_new ();
  gtk_widget_show (calendar4);
  gtk_fixed_put (GTK_FIXED (fixed4), calendar4, 160, 72);
  gtk_widget_set_size_request (calendar4, 216, 160);
  gtk_calendar_display_options (GTK_CALENDAR (calendar4),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  Gym_registration = gtk_label_new (_("Gym registration:"));
  gtk_widget_show (Gym_registration);
  gtk_fixed_put (GTK_FIXED (fixed4), Gym_registration, 168, 8);
  gtk_widget_set_size_request (Gym_registration, 160, 24);

  center = gtk_label_new (_("Center:"));
  gtk_widget_show (center);
  gtk_fixed_put (GTK_FIXED (fixed4), center, 40, 40);
  gtk_widget_set_size_request (center, 88, 24);

  Register = gtk_button_new_with_mnemonic (_("Register"));
  gtk_widget_show (Register);
  gtk_fixed_put (GTK_FIXED (fixed4), Register, 184, 264);
  gtk_widget_set_size_request (Register, 136, 32);

  Start_date = gtk_label_new (_("Start date:"));
  gtk_widget_show (Start_date);
  gtk_fixed_put (GTK_FIXED (fixed4), Start_date, 48, 72);
  gtk_widget_set_size_request (Start_date, 96, 24);

  button8 = gtk_button_new_with_mnemonic (_("Join course as coach "));
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed4), button8, 72, 408);
  gtk_widget_set_size_request (button8, 160, 32);

  button9 = gtk_button_new_with_mnemonic (_("Reserve Equipment"));
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed4), button9, 264, 408);
  gtk_widget_set_size_request (button9, 160, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Espace_Coach, Espace_Coach, "Espace_Coach");
  GLADE_HOOKUP_OBJECT (Espace_Coach, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Espace_Coach, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (Espace_Coach, comboboxentry14, "comboboxentry14");
  GLADE_HOOKUP_OBJECT (Espace_Coach, calendar4, "calendar4");
  GLADE_HOOKUP_OBJECT (Espace_Coach, Gym_registration, "Gym_registration");
  GLADE_HOOKUP_OBJECT (Espace_Coach, center, "center");
  GLADE_HOOKUP_OBJECT (Espace_Coach, Register, "Register");
  GLADE_HOOKUP_OBJECT (Espace_Coach, Start_date, "Start_date");
  GLADE_HOOKUP_OBJECT (Espace_Coach, button8, "button8");
  GLADE_HOOKUP_OBJECT (Espace_Coach, button9, "button9");

  return Espace_Coach;
}

GtkWidget*
create_Espace_inscription (void)
{
  GtkWidget *Espace_inscription;
  GtkWidget *fixed5;
  GtkWidget *entry13;
  GtkWidget *entry14;
  GtkWidget *entry16;
  GtkWidget *label13;
  GtkWidget *label17;
  GtkWidget *entry20;
  GtkWidget *label23;
  GtkWidget *label16;
  GtkWidget *label22;
  GtkWidget *combobox1;
  GtkWidget *entry21;
  GtkWidget *label24;
  GtkWidget *image4;
  GtkWidget *_;
  GtkWidget *radiobutton6;
  GSList *radiobutton6_group = NULL;
  GtkWidget *radiobutton5;
  GtkWidget *image35;
  GtkWidget *image36;
  GtkWidget *image38;
  GtkWidget *image39;
  GtkWidget *Member;
  GtkWidget *Role;
  GtkWidget *button6;
  GtkWidget *button7;
  GtkWidget *image41;
  GtkWidget *image42;
  GtkWidget *image40;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *label15;
  GtkWidget *label14;
  GtkWidget *Coach;

  Espace_inscription = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Espace_inscription), _("Espace inscription"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Espace_inscription), fixed5);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed5), entry13, 144, 104);
  gtk_widget_set_size_request (entry13, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed5), entry14, 144, 136);
  gtk_widget_set_size_request (entry14, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  entry16 = gtk_entry_new ();
  gtk_widget_show (entry16);
  gtk_fixed_put (GTK_FIXED (fixed5), entry16, 144, 224);
  gtk_widget_set_size_request (entry16, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 8226);

  label13 = gtk_label_new (_("First name "));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed5), label13, 40, 104);
  gtk_widget_set_size_request (label13, 80, 16);

  label17 = gtk_label_new (_("Phone "));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed5), label17, 40, 224);
  gtk_widget_set_size_request (label17, 80, 16);

  entry20 = gtk_entry_new ();
  gtk_widget_show (entry20);
  gtk_fixed_put (GTK_FIXED (fixed5), entry20, 144, 256);
  gtk_widget_set_size_request (entry20, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry20), 8226);

  label23 = gtk_label_new (_("Subcription Type"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed5), label23, 24, 288);
  gtk_widget_set_size_request (label23, 120, 16);

  label16 = gtk_label_new (_("Gender "));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed5), label16, 40, 200);
  gtk_widget_set_size_request (label16, 80, 16);

  label22 = gtk_label_new (_("Email"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed5), label22, 56, 256);
  gtk_widget_set_size_request (label22, 49, 17);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox1, 112, 400);
  gtk_widget_set_size_request (combobox1, 33, 31);

  entry21 = gtk_entry_new ();
  gtk_widget_show (entry21);
  gtk_fixed_put (GTK_FIXED (fixed5), entry21, 144, 320);
  gtk_widget_set_size_request (entry21, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry21), 8226);

  label24 = gtk_label_new (_("Password"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed5), label24, 48, 320);
  gtk_widget_set_size_request (label24, 72, 16);

  image4 = create_pixmap (Espace_inscription, "Capture d'écran 2025-10-11 030035.png");
  gtk_widget_show (image4);
  gtk_fixed_put (GTK_FIXED (fixed5), image4, 168, 8);
  gtk_widget_set_size_request (image4, 96, 96);

  _ = gtk_combo_box_entry_new_text ();
  gtk_widget_show (_);
  gtk_fixed_put (GTK_FIXED (fixed5), _, 144, 288);
  gtk_widget_set_size_request (_, 160, 24);
  gtk_container_set_border_width (GTK_CONTAINER (_), 1);
  gtk_combo_box_append_text (GTK_COMBO_BOX (_), _(" "));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("Female"));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton6, 256, 200);
  gtk_widget_set_size_request (radiobutton6, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton6_group);
  radiobutton6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("Male"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton5, 144, 200);
  gtk_widget_set_size_request (radiobutton5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton6_group);
  radiobutton6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  image35 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_fixed_put (GTK_FIXED (fixed5), image35, 312, 104);
  gtk_widget_set_size_request (image35, 21, 21);

  image36 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_fixed_put (GTK_FIXED (fixed5), image36, 312, 136);
  gtk_widget_set_size_request (image36, 21, 21);

  image38 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image38);
  gtk_fixed_put (GTK_FIXED (fixed5), image38, 312, 224);
  gtk_widget_set_size_request (image38, 21, 21);

  image39 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_fixed_put (GTK_FIXED (fixed5), image39, 312, 256);
  gtk_widget_set_size_request (image39, 21, 21);

  Member = gtk_radio_button_new_with_mnemonic (NULL, _("Member"));
  gtk_widget_show (Member);
  gtk_fixed_put (GTK_FIXED (fixed5), Member, 248, 352);
  gtk_widget_set_size_request (Member, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (Member), radiobutton6_group);
  radiobutton6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (Member));

  Role = gtk_label_new (_("Role"));
  gtk_widget_show (Role);
  gtk_fixed_put (GTK_FIXED (fixed5), Role, 64, 352);
  gtk_widget_set_size_request (Role, 49, 17);

  button6 = gtk_button_new_with_mnemonic (_("sign up"));
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed5), button6, 144, 408);
  gtk_widget_set_size_request (button6, 66, 29);

  button7 = gtk_button_new_with_mnemonic (_("Delete"));
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed5), button7, 224, 408);
  gtk_widget_set_size_request (button7, 66, 29);

  image41 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image41);
  gtk_fixed_put (GTK_FIXED (fixed5), image41, 240, 384);
  gtk_widget_set_size_request (image41, 21, 21);

  image42 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image42);
  gtk_fixed_put (GTK_FIXED (fixed5), image42, 168, 384);
  gtk_widget_set_size_request (image42, 21, 21);

  image40 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image40);
  gtk_fixed_put (GTK_FIXED (fixed5), image40, 312, 320);
  gtk_widget_set_size_request (image40, 21, 21);

  spinbutton1_adj = gtk_adjustment_new (18, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton1, 144, 168);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  label15 = gtk_label_new (_("Age "));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed5), label15, 32, 176);
  gtk_widget_set_size_request (label15, 88, 16);

  label14 = gtk_label_new (_("Last  name "));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed5), label14, 40, 144);
  gtk_widget_set_size_request (label14, 80, 16);

  Coach = gtk_radio_button_new_with_mnemonic (NULL, _("Coach"));
  gtk_widget_show (Coach);
  gtk_fixed_put (GTK_FIXED (fixed5), Coach, 136, 352);
  gtk_widget_set_size_request (Coach, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (Coach), radiobutton6_group);
  radiobutton6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (Coach));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Espace_inscription, Espace_inscription, "Espace_inscription");
  GLADE_HOOKUP_OBJECT (Espace_inscription, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Espace_inscription, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (Espace_inscription, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (Espace_inscription, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (Espace_inscription, label13, "label13");
  GLADE_HOOKUP_OBJECT (Espace_inscription, label17, "label17");
  GLADE_HOOKUP_OBJECT (Espace_inscription, entry20, "entry20");
  GLADE_HOOKUP_OBJECT (Espace_inscription, label23, "label23");
  GLADE_HOOKUP_OBJECT (Espace_inscription, label16, "label16");
  GLADE_HOOKUP_OBJECT (Espace_inscription, label22, "label22");
  GLADE_HOOKUP_OBJECT (Espace_inscription, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (Espace_inscription, entry21, "entry21");
  GLADE_HOOKUP_OBJECT (Espace_inscription, label24, "label24");
  GLADE_HOOKUP_OBJECT (Espace_inscription, image4, "image4");
  GLADE_HOOKUP_OBJECT (Espace_inscription, _, "_");
  GLADE_HOOKUP_OBJECT (Espace_inscription, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (Espace_inscription, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (Espace_inscription, image35, "image35");
  GLADE_HOOKUP_OBJECT (Espace_inscription, image36, "image36");
  GLADE_HOOKUP_OBJECT (Espace_inscription, image38, "image38");
  GLADE_HOOKUP_OBJECT (Espace_inscription, image39, "image39");
  GLADE_HOOKUP_OBJECT (Espace_inscription, Member, "Member");
  GLADE_HOOKUP_OBJECT (Espace_inscription, Role, "Role");
  GLADE_HOOKUP_OBJECT (Espace_inscription, button6, "button6");
  GLADE_HOOKUP_OBJECT (Espace_inscription, button7, "button7");
  GLADE_HOOKUP_OBJECT (Espace_inscription, image41, "image41");
  GLADE_HOOKUP_OBJECT (Espace_inscription, image42, "image42");
  GLADE_HOOKUP_OBJECT (Espace_inscription, image40, "image40");
  GLADE_HOOKUP_OBJECT (Espace_inscription, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (Espace_inscription, label15, "label15");
  GLADE_HOOKUP_OBJECT (Espace_inscription, label14, "label14");
  GLADE_HOOKUP_OBJECT (Espace_inscription, Coach, "Coach");

  return Espace_inscription;
}

GtkWidget*
create_Gym_Classes (void)
{
  GtkWidget *Gym_Classes;
  GtkWidget *fixed6;
  GtkWidget *entry22;
  GtkWidget *entry27;
  GtkWidget *entry28;
  GtkWidget *entry29;
  GtkWidget *comboboxentry2;
  GtkWidget *calendar3;
  GtkWidget *button12;
  GtkWidget *button11;
  GtkWidget *button10;
  GtkWidget *button13;
  GtkWidget *image20;
  GtkWidget *image21;
  GtkWidget *image22;
  GtkWidget *image23;
  GtkWidget *button28;
  GtkWidget *image16;
  GtkWidget *label25;
  GtkWidget *label28;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label27;
  GtkWidget *label26;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label32;
  GtkWidget *label31;
  GtkWidget *comboboxentry8;

  Gym_Classes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gym_Classes), _("Gym Classes"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Gym_Classes), fixed6);

  entry22 = gtk_entry_new ();
  gtk_widget_show (entry22);
  gtk_fixed_put (GTK_FIXED (fixed6), entry22, 288, 32);
  gtk_widget_set_size_request (entry22, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry22), _("Ex:A3"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry22), 8226);

  entry27 = gtk_entry_new ();
  gtk_widget_show (entry27);
  gtk_fixed_put (GTK_FIXED (fixed6), entry27, 288, 296);
  gtk_widget_set_size_request (entry27, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry27), _("Ex:M3"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry27), 8226);

  entry28 = gtk_entry_new ();
  gtk_widget_show (entry28);
  gtk_fixed_put (GTK_FIXED (fixed6), entry28, 288, 344);
  gtk_widget_set_size_request (entry28, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry28), _("Ex:100"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry28), 8226);

  entry29 = gtk_entry_new ();
  gtk_widget_show (entry29);
  gtk_fixed_put (GTK_FIXED (fixed6), entry29, 288, 392);
  gtk_widget_set_size_request (entry29, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry29), _("Ex:4h/day"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry29), 8226);

  comboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry2);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxentry2, 288, 96);
  gtk_widget_set_size_request (comboboxentry2, 157, 24);

  calendar3 = gtk_calendar_new ();
  gtk_widget_show (calendar3);
  gtk_fixed_put (GTK_FIXED (fixed6), calendar3, 288, 128);
  gtk_widget_set_size_request (calendar3, 216, 120);
  gtk_calendar_display_options (GTK_CALENDAR (calendar3),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  button12 = gtk_button_new_with_mnemonic (_("Delete "));
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed6), button12, 296, 488);
  gtk_widget_set_size_request (button12, 74, 29);

  button11 = gtk_button_new_with_mnemonic (_("Edit"));
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed6), button11, 168, 488);
  gtk_widget_set_size_request (button11, 74, 29);

  button10 = gtk_button_new_with_mnemonic (_("Add"));
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed6), button10, 56, 488);
  gtk_widget_set_size_request (button10, 74, 29);

  button13 = gtk_button_new_with_mnemonic (_("Search"));
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed6), button13, 416, 488);
  gtk_widget_set_size_request (button13, 74, 29);

  image20 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed6), image20, 32, 488);
  gtk_widget_set_size_request (image20, 21, 21);

  image21 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed6), image21, 144, 496);
  gtk_widget_set_size_request (image21, 24, 16);

  image22 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed6), image22, 272, 488);
  gtk_widget_set_size_request (image22, 24, 24);

  image23 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed6), image23, 392, 488);
  gtk_widget_set_size_request (image23, 21, 21);

  button28 = gtk_button_new_with_mnemonic (_("view  stats"));
  gtk_widget_show (button28);
  gtk_fixed_put (GTK_FIXED (fixed6), button28, 200, 432);
  gtk_widget_set_size_request (button28, 152, 40);

  image16 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed6), image16, 456, 32);
  gtk_widget_set_size_request (image16, 21, 21);

  label25 = gtk_label_new (_("ID course :"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed6), label25, 112, 32);
  gtk_widget_set_size_request (label25, 96, 16);

  label28 = gtk_label_new (_("Course Day :"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed6), label28, 112, 128);
  gtk_widget_set_size_request (label28, 96, 16);

  spinbutton3_adj = gtk_adjustment_new (19, 0, 100, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton3, 288, 256);
  gtk_widget_set_size_request (spinbutton3, 60, 27);
  gtk_spin_button_set_snap_to_ticks (GTK_SPIN_BUTTON (spinbutton3), TRUE);

  label27 = gtk_label_new (_("Head coach :"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed6), label27, 112, 96);
  gtk_widget_set_size_request (label27, 96, 16);

  label26 = gtk_label_new (_("Name of course :"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed6), label26, 112, 64);
  gtk_widget_set_size_request (label26, 128, 16);

  label29 = gtk_label_new (_("Course Time "));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed6), label29, 112, 264);
  gtk_widget_set_size_request (label29, 96, 16);

  label30 = gtk_label_new (_("Room/space"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed6), label30, 112, 304);
  gtk_widget_set_size_request (label30, 96, 16);

  label32 = gtk_label_new (_("Duration"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed6), label32, 120, 392);
  gtk_widget_set_size_request (label32, 64, 16);

  label31 = gtk_label_new (_("Max number\n of participants"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed6), label31, 120, 336);
  gtk_widget_set_size_request (label31, 104, 40);

  comboboxentry8 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry8);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxentry8, 288, 64);
  gtk_widget_set_size_request (comboboxentry8, 157, 24);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gym_Classes, Gym_Classes, "Gym_Classes");
  GLADE_HOOKUP_OBJECT (Gym_Classes, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Gym_Classes, entry22, "entry22");
  GLADE_HOOKUP_OBJECT (Gym_Classes, entry27, "entry27");
  GLADE_HOOKUP_OBJECT (Gym_Classes, entry28, "entry28");
  GLADE_HOOKUP_OBJECT (Gym_Classes, entry29, "entry29");
  GLADE_HOOKUP_OBJECT (Gym_Classes, comboboxentry2, "comboboxentry2");
  GLADE_HOOKUP_OBJECT (Gym_Classes, calendar3, "calendar3");
  GLADE_HOOKUP_OBJECT (Gym_Classes, button12, "button12");
  GLADE_HOOKUP_OBJECT (Gym_Classes, button11, "button11");
  GLADE_HOOKUP_OBJECT (Gym_Classes, button10, "button10");
  GLADE_HOOKUP_OBJECT (Gym_Classes, button13, "button13");
  GLADE_HOOKUP_OBJECT (Gym_Classes, image20, "image20");
  GLADE_HOOKUP_OBJECT (Gym_Classes, image21, "image21");
  GLADE_HOOKUP_OBJECT (Gym_Classes, image22, "image22");
  GLADE_HOOKUP_OBJECT (Gym_Classes, image23, "image23");
  GLADE_HOOKUP_OBJECT (Gym_Classes, button28, "button28");
  GLADE_HOOKUP_OBJECT (Gym_Classes, image16, "image16");
  GLADE_HOOKUP_OBJECT (Gym_Classes, label25, "label25");
  GLADE_HOOKUP_OBJECT (Gym_Classes, label28, "label28");
  GLADE_HOOKUP_OBJECT (Gym_Classes, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (Gym_Classes, label27, "label27");
  GLADE_HOOKUP_OBJECT (Gym_Classes, label26, "label26");
  GLADE_HOOKUP_OBJECT (Gym_Classes, label29, "label29");
  GLADE_HOOKUP_OBJECT (Gym_Classes, label30, "label30");
  GLADE_HOOKUP_OBJECT (Gym_Classes, label32, "label32");
  GLADE_HOOKUP_OBJECT (Gym_Classes, label31, "label31");
  GLADE_HOOKUP_OBJECT (Gym_Classes, comboboxentry8, "comboboxentry8");

  return Gym_Classes;
}

GtkWidget*
create_Member_Management (void)
{
  GtkWidget *Member_Management;
  GtkWidget *fixed8;
  GtkWidget *entry37;
  GtkWidget *button21;
  GtkWidget *button22;
  GtkWidget *button23;
  GtkWidget *button24;
  GtkWidget *image28;
  GtkWidget *image29;
  GtkWidget *image30;
  GtkWidget *image31;
  GtkWidget *entry42;
  GtkWidget *entry43;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkWidget *entry44;
  GtkWidget *entry45;
  GtkWidget *comboboxentry12;
  GtkWidget *label40;
  GtkWidget *radiobutton14;
  GSList *radiobutton14_group = NULL;
  GtkWidget *radiobutton13;
  GtkWidget *label83;
  GtkWidget *button31;
  GtkWidget *Show_stats;
  GtkWidget *button32;
  GtkWidget *label77;
  GtkWidget *label78;
  GtkWidget *label79;
  GtkWidget *label80;
  GtkWidget *label81;
  GtkWidget *label82;
  GtkWidget *image32;

  Member_Management = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Member_Management), _("Member Management"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (Member_Management), fixed8);

  entry37 = gtk_entry_new ();
  gtk_widget_show (entry37);
  gtk_fixed_put (GTK_FIXED (fixed8), entry37, 152, 32);
  gtk_widget_set_size_request (entry37, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry37), _("Ex:12561456"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry37), 8226);

  button21 = gtk_button_new_with_mnemonic (_("Add"));
  gtk_widget_show (button21);
  gtk_fixed_put (GTK_FIXED (fixed8), button21, 48, 480);
  gtk_widget_set_size_request (button21, 74, 29);

  button22 = gtk_button_new_with_mnemonic (_("Edit"));
  gtk_widget_show (button22);
  gtk_fixed_put (GTK_FIXED (fixed8), button22, 144, 480);
  gtk_widget_set_size_request (button22, 74, 29);

  button23 = gtk_button_new_with_mnemonic (_("Delete"));
  gtk_widget_show (button23);
  gtk_fixed_put (GTK_FIXED (fixed8), button23, 248, 480);
  gtk_widget_set_size_request (button23, 74, 29);

  button24 = gtk_button_new_with_mnemonic (_("Search"));
  gtk_widget_show (button24);
  gtk_fixed_put (GTK_FIXED (fixed8), button24, 352, 480);
  gtk_widget_set_size_request (button24, 74, 29);

  image28 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed8), image28, 72, 448);
  gtk_widget_set_size_request (image28, 21, 21);

  image29 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed8), image29, 168, 448);
  gtk_widget_set_size_request (image29, 21, 21);

  image30 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed8), image30, 272, 448);
  gtk_widget_set_size_request (image30, 21, 21);

  image31 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (fixed8), image31, 376, 448);
  gtk_widget_set_size_request (image31, 21, 21);

  entry42 = gtk_entry_new ();
  gtk_widget_show (entry42);
  gtk_fixed_put (GTK_FIXED (fixed8), entry42, 152, 80);
  gtk_widget_set_size_request (entry42, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry42), _("Ex:Mohamed"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry42), 8226);

  entry43 = gtk_entry_new ();
  gtk_widget_show (entry43);
  gtk_fixed_put (GTK_FIXED (fixed8), entry43, 152, 128);
  gtk_widget_set_size_request (entry43, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry43), _("Ex:Ben Ali"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry43), 8226);

  spinbutton5_adj = gtk_adjustment_new (18, 0, 100, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton5, 152, 176);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  entry44 = gtk_entry_new ();
  gtk_widget_show (entry44);
  gtk_fixed_put (GTK_FIXED (fixed8), entry44, 152, 272);
  gtk_widget_set_size_request (entry44, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry44), _("Ex:99256485"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry44), 8226);

  entry45 = gtk_entry_new ();
  gtk_widget_show (entry45);
  gtk_fixed_put (GTK_FIXED (fixed8), entry45, 152, 312);
  gtk_widget_set_size_request (entry45, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry45), _("Ex:Esprit@esprit.tn"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry45), 8226);

  comboboxentry12 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry12);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxentry12, 152, 352);
  gtk_widget_set_size_request (comboboxentry12, 189, 29);

  label40 = gtk_label_new (_("ID-Member:"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed8), label40, 16, 40);
  gtk_widget_set_size_request (label40, 96, 16);

  radiobutton14 = gtk_radio_button_new_with_mnemonic (NULL, _("Female"));
  gtk_widget_show (radiobutton14);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton14, 152, 232);
  gtk_widget_set_size_request (radiobutton14, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton14), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton14));

  radiobutton13 = gtk_radio_button_new_with_mnemonic (NULL, _("Male"));
  gtk_widget_show (radiobutton13);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton13, 240, 232);
  gtk_widget_set_size_request (radiobutton13, 72, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton13), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton13));

  label83 = gtk_label_new (_("Subscription Type:"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed8), label83, 16, 352);
  gtk_widget_set_size_request (label83, 128, 24);

  button31 = gtk_button_new_with_mnemonic (_("Private Coach \n      Request"));
  gtk_widget_show (button31);
  gtk_fixed_put (GTK_FIXED (fixed8), button31, 24, 392);
  gtk_widget_set_size_request (button31, 120, 48);

  Show_stats = gtk_button_new_with_mnemonic (_("Show stats"));
  gtk_widget_show (Show_stats);
  gtk_fixed_put (GTK_FIXED (fixed8), Show_stats, 176, 392);
  gtk_widget_set_size_request (Show_stats, 96, 48);

  button32 = gtk_button_new_with_mnemonic (_("Join Course"));
  gtk_widget_show (button32);
  gtk_fixed_put (GTK_FIXED (fixed8), button32, 288, 392);
  gtk_widget_set_size_request (button32, 96, 48);

  label77 = gtk_label_new (_("First Name:"));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed8), label77, 24, 88);
  gtk_widget_set_size_request (label77, 80, 16);

  label78 = gtk_label_new (_("Last Name:"));
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed8), label78, 24, 136);
  gtk_widget_set_size_request (label78, 72, 16);

  label79 = gtk_label_new (_("Age:"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed8), label79, 24, 176);
  gtk_widget_set_size_request (label79, 40, 25);

  label80 = gtk_label_new (_("Gender:"));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed8), label80, 24, 232);
  gtk_widget_set_size_request (label80, 49, 17);

  label81 = gtk_label_new (_("Phone:"));
  gtk_widget_show (label81);
  gtk_fixed_put (GTK_FIXED (fixed8), label81, 24, 272);
  gtk_widget_set_size_request (label81, 49, 17);

  label82 = gtk_label_new (_("Email:"));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed8), label82, 24, 312);
  gtk_widget_set_size_request (label82, 49, 17);

  image32 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_fixed_put (GTK_FIXED (fixed8), image32, 320, 32);
  gtk_widget_set_size_request (image32, 21, 21);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Member_Management, Member_Management, "Member_Management");
  GLADE_HOOKUP_OBJECT (Member_Management, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (Member_Management, entry37, "entry37");
  GLADE_HOOKUP_OBJECT (Member_Management, button21, "button21");
  GLADE_HOOKUP_OBJECT (Member_Management, button22, "button22");
  GLADE_HOOKUP_OBJECT (Member_Management, button23, "button23");
  GLADE_HOOKUP_OBJECT (Member_Management, button24, "button24");
  GLADE_HOOKUP_OBJECT (Member_Management, image28, "image28");
  GLADE_HOOKUP_OBJECT (Member_Management, image29, "image29");
  GLADE_HOOKUP_OBJECT (Member_Management, image30, "image30");
  GLADE_HOOKUP_OBJECT (Member_Management, image31, "image31");
  GLADE_HOOKUP_OBJECT (Member_Management, entry42, "entry42");
  GLADE_HOOKUP_OBJECT (Member_Management, entry43, "entry43");
  GLADE_HOOKUP_OBJECT (Member_Management, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (Member_Management, entry44, "entry44");
  GLADE_HOOKUP_OBJECT (Member_Management, entry45, "entry45");
  GLADE_HOOKUP_OBJECT (Member_Management, comboboxentry12, "comboboxentry12");
  GLADE_HOOKUP_OBJECT (Member_Management, label40, "label40");
  GLADE_HOOKUP_OBJECT (Member_Management, radiobutton14, "radiobutton14");
  GLADE_HOOKUP_OBJECT (Member_Management, radiobutton13, "radiobutton13");
  GLADE_HOOKUP_OBJECT (Member_Management, label83, "label83");
  GLADE_HOOKUP_OBJECT (Member_Management, button31, "button31");
  GLADE_HOOKUP_OBJECT (Member_Management, Show_stats, "Show_stats");
  GLADE_HOOKUP_OBJECT (Member_Management, button32, "button32");
  GLADE_HOOKUP_OBJECT (Member_Management, label77, "label77");
  GLADE_HOOKUP_OBJECT (Member_Management, label78, "label78");
  GLADE_HOOKUP_OBJECT (Member_Management, label79, "label79");
  GLADE_HOOKUP_OBJECT (Member_Management, label80, "label80");
  GLADE_HOOKUP_OBJECT (Member_Management, label81, "label81");
  GLADE_HOOKUP_OBJECT (Member_Management, label82, "label82");
  GLADE_HOOKUP_OBJECT (Member_Management, image32, "image32");

  return Member_Management;
}

GtkWidget*
create_private_coach_request (void)
{
  GtkWidget *private_coach_request;
  GtkWidget *fixed9;
  GtkWidget *entry39;
  GtkWidget *textview2;
  GtkWidget *calendar1;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *comboboxentry3;
  GtkWidget *label46;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkWidget *label47;
  GtkWidget *label48;
  GtkWidget *button25;
  GtkWidget *button26;
  GtkWidget *label73;

  private_coach_request = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (private_coach_request), _("private coach request"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (private_coach_request), fixed9);

  entry39 = gtk_entry_new ();
  gtk_widget_show (entry39);
  gtk_fixed_put (GTK_FIXED (fixed9), entry39, 280, 56);
  gtk_widget_set_size_request (entry39, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry39), 8226);

  textview2 = gtk_text_view_new ();
  gtk_widget_show (textview2);
  gtk_fixed_put (GTK_FIXED (fixed9), textview2, 280, 392);
  gtk_widget_set_size_request (textview2, 160, 40);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed9), calendar1, 280, 240);
  gtk_widget_set_size_request (calendar1, 224, 120);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label44 = gtk_label_new (_("ID member"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed9), label44, 160, 56);
  gtk_widget_set_size_request (label44, 0, 0);

  label45 = gtk_label_new (_("Coach Name "));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed9), label45, 152, 128);
  gtk_widget_set_size_request (label45, 88, 16);

  comboboxentry3 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry3);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentry3, 280, 120);
  gtk_widget_set_size_request (comboboxentry3, 189, 29);

  label46 = gtk_label_new (_("Preffered time"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed9), label46, 152, 184);
  gtk_widget_set_size_request (label46, 104, 24);

  spinbutton4_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton4, 280, 184);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  label47 = gtk_label_new (_("Preffered Date"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed9), label47, 152, 248);
  gtk_widget_set_size_request (label47, 104, 16);

  label48 = gtk_label_new (_("Objectif"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed9), label48, 160, 392);
  gtk_widget_set_size_request (label48, 56, 24);

  button25 = gtk_button_new_with_mnemonic (_("submit"));
  gtk_widget_show (button25);
  gtk_fixed_put (GTK_FIXED (fixed9), button25, 176, 472);
  gtk_widget_set_size_request (button25, 74, 29);

  button26 = gtk_button_new_with_mnemonic (_("cancel"));
  gtk_widget_show (button26);
  gtk_fixed_put (GTK_FIXED (fixed9), button26, 360, 472);
  gtk_widget_set_size_request (button26, 74, 29);

  label73 = gtk_label_new (_("Incorrect ID"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed9), label73, 168, 504);
  gtk_widget_set_size_request (label73, 88, 16);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (private_coach_request, private_coach_request, "private_coach_request");
  GLADE_HOOKUP_OBJECT (private_coach_request, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (private_coach_request, entry39, "entry39");
  GLADE_HOOKUP_OBJECT (private_coach_request, textview2, "textview2");
  GLADE_HOOKUP_OBJECT (private_coach_request, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (private_coach_request, label44, "label44");
  GLADE_HOOKUP_OBJECT (private_coach_request, label45, "label45");
  GLADE_HOOKUP_OBJECT (private_coach_request, comboboxentry3, "comboboxentry3");
  GLADE_HOOKUP_OBJECT (private_coach_request, label46, "label46");
  GLADE_HOOKUP_OBJECT (private_coach_request, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (private_coach_request, label47, "label47");
  GLADE_HOOKUP_OBJECT (private_coach_request, label48, "label48");
  GLADE_HOOKUP_OBJECT (private_coach_request, button25, "button25");
  GLADE_HOOKUP_OBJECT (private_coach_request, button26, "button26");
  GLADE_HOOKUP_OBJECT (private_coach_request, label73, "label73");

  return private_coach_request;
}

GtkWidget*
create_join_course (void)
{
  GtkWidget *join_course;
  GtkWidget *fixed13;
  GtkWidget *entry40;
  GtkWidget *calendar2;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *label70;
  GtkWidget *label55;
  GtkWidget *label71;
  GtkWidget *label54;
  GtkWidget *button30;
  GtkWidget *label72;
  GtkWidget *checkbutton4;
  GtkWidget *checkbutton5;
  GtkWidget *checkbutton6;
  GtkWidget *checkbutton7;
  GtkWidget *radiobutton10;
  GSList *radiobutton10_group = NULL;
  GtkWidget *radiobutton11;
  GtkWidget *radiobutton12;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton3;
  GtkWidget *entry41;
  GtkWidget *label52;
  GtkWidget *image5;
  GtkWidget *label53;
  GtkWidget *ID_Course;
  GtkWidget *Coach_Name_;
  GtkWidget *comboboxentry7;
  GtkWidget *comboboxentry11;

  join_course = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (join_course), _("join course"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (join_course), fixed13);

  entry40 = gtk_entry_new ();
  gtk_widget_show (entry40);
  gtk_fixed_put (GTK_FIXED (fixed13), entry40, 176, 72);
  gtk_widget_set_size_request (entry40, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry40), 8226);

  calendar2 = gtk_calendar_new ();
  gtk_widget_show (calendar2);
  gtk_fixed_put (GTK_FIXED (fixed13), calendar2, 168, 296);
  gtk_widget_set_size_request (calendar2, 216, 160);
  gtk_calendar_display_options (GTK_CALENDAR (calendar2),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  spinbutton2_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton2, 176, 216);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  label70 = gtk_label_new (_("Level"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed13), label70, 64, 192);
  gtk_widget_set_size_request (label70, 49, 17);

  label55 = gtk_label_new (_("Duration"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed13), label55, 56, 224);
  gtk_widget_set_size_request (label55, 88, 16);

  label71 = gtk_label_new (_("Preferred Days"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed13), label71, 64, 264);
  gtk_widget_set_size_request (label71, 112, 16);

  label54 = gtk_label_new (_("course date"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed13), label54, 56, 296);
  gtk_widget_set_size_request (label54, 104, 16);

  button30 = gtk_button_new_with_mnemonic (_("Join"));
  gtk_widget_show (button30);
  gtk_fixed_put (GTK_FIXED (fixed13), button30, 240, 472);
  gtk_widget_set_size_request (button30, 74, 29);

  label72 = gtk_label_new (_("Invalid ID"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed13), label72, 240, 504);
  gtk_widget_set_size_request (label72, 72, 16);

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("4"));
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed13), checkbutton4, 312, 256);
  gtk_widget_set_size_request (checkbutton4, 40, 24);

  checkbutton5 = gtk_check_button_new_with_mnemonic (_("5"));
  gtk_widget_show (checkbutton5);
  gtk_fixed_put (GTK_FIXED (fixed13), checkbutton5, 352, 256);
  gtk_widget_set_size_request (checkbutton5, 40, 24);

  checkbutton6 = gtk_check_button_new_with_mnemonic (_("6"));
  gtk_widget_show (checkbutton6);
  gtk_fixed_put (GTK_FIXED (fixed13), checkbutton6, 392, 256);
  gtk_widget_set_size_request (checkbutton6, 40, 24);

  checkbutton7 = gtk_check_button_new_with_mnemonic (_("7"));
  gtk_widget_show (checkbutton7);
  gtk_fixed_put (GTK_FIXED (fixed13), checkbutton7, 432, 256);
  gtk_widget_set_size_request (checkbutton7, 40, 24);

  radiobutton10 = gtk_radio_button_new_with_mnemonic (NULL, _("Beginner"));
  gtk_widget_show (radiobutton10);
  gtk_fixed_put (GTK_FIXED (fixed13), radiobutton10, 176, 184);
  gtk_widget_set_size_request (radiobutton10, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton10), radiobutton10_group);
  radiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton10));

  radiobutton11 = gtk_radio_button_new_with_mnemonic (NULL, _("Intermediate "));
  gtk_widget_show (radiobutton11);
  gtk_fixed_put (GTK_FIXED (fixed13), radiobutton11, 272, 184);
  gtk_widget_set_size_request (radiobutton11, 120, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11), radiobutton10_group);
  radiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11));

  radiobutton12 = gtk_radio_button_new_with_mnemonic (NULL, _("Advanced"));
  gtk_widget_show (radiobutton12);
  gtk_fixed_put (GTK_FIXED (fixed13), radiobutton12, 392, 184);
  gtk_widget_set_size_request (radiobutton12, 96, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton12), radiobutton10_group);
  radiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton12));

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("1"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed13), checkbutton1, 176, 256);
  gtk_widget_set_size_request (checkbutton1, 40, 24);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("2"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed13), checkbutton2, 224, 256);
  gtk_widget_set_size_request (checkbutton2, 40, 24);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("3"));
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed13), checkbutton3, 264, 256);
  gtk_widget_set_size_request (checkbutton3, 40, 24);

  entry41 = gtk_entry_new ();
  gtk_widget_show (entry41);
  gtk_fixed_put (GTK_FIXED (fixed13), entry41, 176, 32);
  gtk_widget_set_size_request (entry41, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry41), 8226);

  label52 = gtk_label_new (_("ID Member"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed13), label52, 64, 80);
  gtk_widget_set_size_request (label52, 88, 16);

  image5 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_fixed_put (GTK_FIXED (fixed13), image5, 344, 80);
  gtk_widget_set_size_request (image5, 21, 21);

  label53 = gtk_label_new (_("Course name "));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed13), label53, 64, 152);
  gtk_widget_set_size_request (label53, 96, 16);

  ID_Course = gtk_label_new (_("ID course"));
  gtk_widget_show (ID_Course);
  gtk_fixed_put (GTK_FIXED (fixed13), ID_Course, 64, 32);
  gtk_widget_set_size_request (ID_Course, 80, 24);

  Coach_Name_ = gtk_label_new (_("coach name"));
  gtk_widget_show (Coach_Name_);
  gtk_fixed_put (GTK_FIXED (fixed13), Coach_Name_, 72, 120);
  gtk_widget_set_size_request (Coach_Name_, 80, 16);

  comboboxentry7 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry7);
  gtk_fixed_put (GTK_FIXED (fixed13), comboboxentry7, 176, 152);
  gtk_widget_set_size_request (comboboxentry7, 165, 29);

  comboboxentry11 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry11);
  gtk_fixed_put (GTK_FIXED (fixed13), comboboxentry11, 176, 112);
  gtk_widget_set_size_request (comboboxentry11, 165, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (join_course, join_course, "join_course");
  GLADE_HOOKUP_OBJECT (join_course, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (join_course, entry40, "entry40");
  GLADE_HOOKUP_OBJECT (join_course, calendar2, "calendar2");
  GLADE_HOOKUP_OBJECT (join_course, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (join_course, label70, "label70");
  GLADE_HOOKUP_OBJECT (join_course, label55, "label55");
  GLADE_HOOKUP_OBJECT (join_course, label71, "label71");
  GLADE_HOOKUP_OBJECT (join_course, label54, "label54");
  GLADE_HOOKUP_OBJECT (join_course, button30, "button30");
  GLADE_HOOKUP_OBJECT (join_course, label72, "label72");
  GLADE_HOOKUP_OBJECT (join_course, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (join_course, checkbutton5, "checkbutton5");
  GLADE_HOOKUP_OBJECT (join_course, checkbutton6, "checkbutton6");
  GLADE_HOOKUP_OBJECT (join_course, checkbutton7, "checkbutton7");
  GLADE_HOOKUP_OBJECT (join_course, radiobutton10, "radiobutton10");
  GLADE_HOOKUP_OBJECT (join_course, radiobutton11, "radiobutton11");
  GLADE_HOOKUP_OBJECT (join_course, radiobutton12, "radiobutton12");
  GLADE_HOOKUP_OBJECT (join_course, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (join_course, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (join_course, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (join_course, entry41, "entry41");
  GLADE_HOOKUP_OBJECT (join_course, label52, "label52");
  GLADE_HOOKUP_OBJECT (join_course, image5, "image5");
  GLADE_HOOKUP_OBJECT (join_course, label53, "label53");
  GLADE_HOOKUP_OBJECT (join_course, ID_Course, "ID_Course");
  GLADE_HOOKUP_OBJECT (join_course, Coach_Name_, "Coach_Name_");
  GLADE_HOOKUP_OBJECT (join_course, comboboxentry7, "comboboxentry7");
  GLADE_HOOKUP_OBJECT (join_course, comboboxentry11, "comboboxentry11");

  return join_course;
}

GtkWidget*
create_Gym_classes_stats (void)
{
  GtkWidget *Gym_classes_stats;
  GtkWidget *fixed14;
  GtkWidget *label57;
  GtkWidget *textview3;
  GtkWidget *textview4;
  GtkWidget *textview5;
  GtkWidget *textview6;
  GtkWidget *textview7;
  GtkWidget *label58;
  GtkWidget *image44;
  GtkWidget *men;
  GtkWidget *label59;
  GtkWidget *label61;

  Gym_classes_stats = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gym_classes_stats), _("Gym classes stats"));

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (Gym_classes_stats), fixed14);

  label57 = gtk_label_new (_("Least popular course:"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed14), label57, 40, 296);
  gtk_widget_set_size_request (label57, 144, 32);

  textview3 = gtk_text_view_new ();
  gtk_widget_show (textview3);
  gtk_fixed_put (GTK_FIXED (fixed14), textview3, 192, 104);
  gtk_widget_set_size_request (textview3, 128, 32);

  textview4 = gtk_text_view_new ();
  gtk_widget_show (textview4);
  gtk_fixed_put (GTK_FIXED (fixed14), textview4, 192, 208);
  gtk_widget_set_size_request (textview4, 128, 32);

  textview5 = gtk_text_view_new ();
  gtk_widget_show (textview5);
  gtk_fixed_put (GTK_FIXED (fixed14), textview5, 192, 296);
  gtk_widget_set_size_request (textview5, 128, 32);

  textview6 = gtk_text_view_new ();
  gtk_widget_show (textview6);
  gtk_fixed_put (GTK_FIXED (fixed14), textview6, 560, 144);
  gtk_widget_set_size_request (textview6, 136, 48);

  textview7 = gtk_text_view_new ();
  gtk_widget_show (textview7);
  gtk_fixed_put (GTK_FIXED (fixed14), textview7, 560, 328);
  gtk_widget_set_size_request (textview7, 136, 48);

  label58 = gtk_label_new (_("Most popular course:"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed14), label58, 32, 208);
  gtk_widget_set_size_request (label58, 160, 24);

  image44 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image44);
  gtk_fixed_put (GTK_FIXED (fixed14), image44, 344, 472);
  gtk_widget_set_size_request (image44, 48, 53);

  men = gtk_label_new (_("Total number of courses:"));
  gtk_widget_show (men);
  gtk_fixed_put (GTK_FIXED (fixed14), men, 8, 104);
  gtk_widget_set_size_request (men, 176, 32);

  label59 = gtk_label_new (_("Female participation by course:"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed14), label59, 336, 160);
  gtk_widget_set_size_request (label59, 216, 24);

  label61 = gtk_label_new (_("Male participation by course:"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed14), label61, 336, 344);
  gtk_widget_set_size_request (label61, 216, 24);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gym_classes_stats, Gym_classes_stats, "Gym_classes_stats");
  GLADE_HOOKUP_OBJECT (Gym_classes_stats, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (Gym_classes_stats, label57, "label57");
  GLADE_HOOKUP_OBJECT (Gym_classes_stats, textview3, "textview3");
  GLADE_HOOKUP_OBJECT (Gym_classes_stats, textview4, "textview4");
  GLADE_HOOKUP_OBJECT (Gym_classes_stats, textview5, "textview5");
  GLADE_HOOKUP_OBJECT (Gym_classes_stats, textview6, "textview6");
  GLADE_HOOKUP_OBJECT (Gym_classes_stats, textview7, "textview7");
  GLADE_HOOKUP_OBJECT (Gym_classes_stats, label58, "label58");
  GLADE_HOOKUP_OBJECT (Gym_classes_stats, image44, "image44");
  GLADE_HOOKUP_OBJECT (Gym_classes_stats, men, "men");
  GLADE_HOOKUP_OBJECT (Gym_classes_stats, label59, "label59");
  GLADE_HOOKUP_OBJECT (Gym_classes_stats, label61, "label61");

  return Gym_classes_stats;
}

GtkWidget*
create_Member_stats (void)
{
  GtkWidget *Member_stats;
  GtkWidget *fixed16;
  GtkWidget *textview12;
  GtkWidget *textview13;
  GtkWidget *textview14;
  GtkWidget *_;
  GtkWidget *label68;
  GtkWidget *radiobutton7;
  GSList *radiobutton7_group = NULL;
  GtkWidget *radiobutton8;
  GtkWidget *radiobutton9;
  GtkWidget *label67;
  GtkWidget *label69;
  GtkWidget *label74;
  GtkWidget *comboboxentry10;

  Member_stats = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Member_stats), _("Member stats"));

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (Member_stats), fixed16);

  textview12 = gtk_text_view_new ();
  gtk_widget_show (textview12);
  gtk_fixed_put (GTK_FIXED (fixed16), textview12, 280, 32);
  gtk_widget_set_size_request (textview12, 72, 40);

  textview13 = gtk_text_view_new ();
  gtk_widget_show (textview13);
  gtk_fixed_put (GTK_FIXED (fixed16), textview13, 280, 88);
  gtk_widget_set_size_request (textview13, 72, 40);

  textview14 = gtk_text_view_new ();
  gtk_widget_show (textview14);
  gtk_fixed_put (GTK_FIXED (fixed16), textview14, 280, 240);
  gtk_widget_set_size_request (textview14, 80, 40);

  _ = gtk_label_new (_("Number of classes attended"));
  gtk_widget_show (_);
  gtk_fixed_put (GTK_FIXED (fixed16), _, 48, 48);
  gtk_widget_set_size_request (_, 208, 16);

  label68 = gtk_label_new (_("Coach Performance Ranking"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed16), label68, 48, 192);
  gtk_widget_set_size_request (label68, 200, 32);

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("Bad"));
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed16), radiobutton7, 264, 192);
  gtk_widget_set_size_request (radiobutton7, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, _("Good"));
  gtk_widget_show (radiobutton8);
  gtk_fixed_put (GTK_FIXED (fixed16), radiobutton8, 328, 192);
  gtk_widget_set_size_request (radiobutton8, 72, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  radiobutton9 = gtk_radio_button_new_with_mnemonic (NULL, _("Excellent"));
  gtk_widget_show (radiobutton9);
  gtk_fixed_put (GTK_FIXED (fixed16), radiobutton9, 400, 192);
  gtk_widget_set_size_request (radiobutton9, 88, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton9), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton9));

  label67 = gtk_label_new (_("Favorite class"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed16), label67, 40, 96);
  gtk_widget_set_size_request (label67, 128, 17);

  label69 = gtk_label_new (_("Consistency Score:"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed16), label69, 48, 240);
  gtk_widget_set_size_request (label69, 144, 16);

  label74 = gtk_label_new (_("Coach Name"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed16), label74, 48, 160);
  gtk_widget_set_size_request (label74, 96, 16);

  comboboxentry10 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry10);
  gtk_fixed_put (GTK_FIXED (fixed16), comboboxentry10, 280, 144);
  gtk_widget_set_size_request (comboboxentry10, 125, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Member_stats, Member_stats, "Member_stats");
  GLADE_HOOKUP_OBJECT (Member_stats, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (Member_stats, textview12, "textview12");
  GLADE_HOOKUP_OBJECT (Member_stats, textview13, "textview13");
  GLADE_HOOKUP_OBJECT (Member_stats, textview14, "textview14");
  GLADE_HOOKUP_OBJECT (Member_stats, _, "_");
  GLADE_HOOKUP_OBJECT (Member_stats, label68, "label68");
  GLADE_HOOKUP_OBJECT (Member_stats, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (Member_stats, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (Member_stats, radiobutton9, "radiobutton9");
  GLADE_HOOKUP_OBJECT (Member_stats, label67, "label67");
  GLADE_HOOKUP_OBJECT (Member_stats, label69, "label69");
  GLADE_HOOKUP_OBJECT (Member_stats, label74, "label74");
  GLADE_HOOKUP_OBJECT (Member_stats, comboboxentry10, "comboboxentry10");

  return Member_stats;
}

GtkWidget*
create_window_coach (void)
{
  GtkWidget *window_coach;
  GtkWidget *fixed17;
  GtkWidget *label98;
  GtkWidget *label99;
  GtkWidget *label100;
  GtkWidget *label101;
  GtkWidget *label102;
  GtkWidget *First_name;
  GtkWidget *Last_name;
  GtkWidget *label103;
  GtkWidget *entry_id;
  GtkWidget *entry_first_name;
  GtkWidget *entry_last_name;
  GtkObject *spin_age_adj;
  GtkWidget *spin_age;
  GtkWidget *entry_phone;
  GtkWidget *entry_email;
  GtkWidget *entry_dispo;
  GtkWidget *label_message;
  GtkWidget *radio_male;
  GSList *radio_male_group = NULL;
  GtkWidget *radio_female;
  GtkWidget *button_delete;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image45;
  GtkWidget *label104;
  GtkWidget *button_edit;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image46;
  GtkWidget *label105;
  GtkWidget *button_add;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image47;
  GtkWidget *label106;
  GtkWidget *button_search;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image48;
  GtkWidget *label107;
  GtkWidget *ID;
  GtkWidget *combo_specialite;
  GtkWidget *button_view_stats;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image49;
  GtkWidget *label108;

  window_coach = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_coach), _("Coach Managemet"));

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (window_coach), fixed17);

  label98 = gtk_label_new (_("Gender"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed17), label98, 32, 144);
  gtk_widget_set_size_request (label98, 49, 17);

  label99 = gtk_label_new (_("Age"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed17), label99, 32, 176);
  gtk_widget_set_size_request (label99, 49, 17);

  label100 = gtk_label_new (_("Speciality"));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed17), label100, 24, 224);
  gtk_widget_set_size_request (label100, 88, 16);

  label101 = gtk_label_new (_("Phone"));
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed17), label101, 40, 256);
  gtk_widget_set_size_request (label101, 57, 17);

  label102 = gtk_label_new (_("E-mail"));
  gtk_widget_show (label102);
  gtk_fixed_put (GTK_FIXED (fixed17), label102, 40, 288);
  gtk_widget_set_size_request (label102, 57, 17);

  First_name = gtk_label_new (_("First name"));
  gtk_widget_show (First_name);
  gtk_fixed_put (GTK_FIXED (fixed17), First_name, 32, 65);
  gtk_widget_set_size_request (First_name, 96, 16);

  Last_name = gtk_label_new (_("Last name"));
  gtk_widget_show (Last_name);
  gtk_fixed_put (GTK_FIXED (fixed17), Last_name, 32, 104);
  gtk_widget_set_size_request (Last_name, 88, 16);

  label103 = gtk_label_new (_("Disponibility"));
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed17), label103, 16, 320);
  gtk_widget_set_size_request (label103, 112, 17);

  entry_id = gtk_entry_new ();
  gtk_widget_show (entry_id);
  gtk_fixed_put (GTK_FIXED (fixed17), entry_id, 136, 24);
  gtk_widget_set_size_request (entry_id, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id), 8226);

  entry_first_name = gtk_entry_new ();
  gtk_widget_show (entry_first_name);
  gtk_fixed_put (GTK_FIXED (fixed17), entry_first_name, 136, 56);
  gtk_widget_set_size_request (entry_first_name, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_first_name), 8226);

  entry_last_name = gtk_entry_new ();
  gtk_widget_show (entry_last_name);
  gtk_fixed_put (GTK_FIXED (fixed17), entry_last_name, 136, 88);
  gtk_widget_set_size_request (entry_last_name, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_last_name), 8226);

  spin_age_adj = gtk_adjustment_new (18, 18, 80, 1, 10, 10);
  spin_age = gtk_spin_button_new (GTK_ADJUSTMENT (spin_age_adj), 1, 0);
  gtk_widget_show (spin_age);
  gtk_fixed_put (GTK_FIXED (fixed17), spin_age, 136, 176);
  gtk_widget_set_size_request (spin_age, 60, 27);

  entry_phone = gtk_entry_new ();
  gtk_widget_show (entry_phone);
  gtk_fixed_put (GTK_FIXED (fixed17), entry_phone, 136, 248);
  gtk_widget_set_size_request (entry_phone, 256, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_phone), 8226);

  entry_email = gtk_entry_new ();
  gtk_widget_show (entry_email);
  gtk_fixed_put (GTK_FIXED (fixed17), entry_email, 136, 280);
  gtk_widget_set_size_request (entry_email, 256, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_email), 8226);

  entry_dispo = gtk_entry_new ();
  gtk_widget_show (entry_dispo);
  gtk_fixed_put (GTK_FIXED (fixed17), entry_dispo, 136, 312);
  gtk_widget_set_size_request (entry_dispo, 256, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_dispo), 8226);

  label_message = gtk_text_view_new ();
  gtk_widget_show (label_message);
  gtk_fixed_put (GTK_FIXED (fixed17), label_message, 104, 416);
  gtk_widget_set_size_request (label_message, 168, 56);

  radio_male = gtk_radio_button_new_with_mnemonic (NULL, _("male"));
  gtk_widget_show (radio_male);
  gtk_fixed_put (GTK_FIXED (fixed17), radio_male, 128, 144);
  gtk_widget_set_size_request (radio_male, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_male), radio_male_group);
  radio_male_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_male));

  radio_female = gtk_radio_button_new_with_mnemonic (NULL, _("female"));
  gtk_widget_show (radio_female);
  gtk_fixed_put (GTK_FIXED (fixed17), radio_female, 280, 144);
  gtk_widget_set_size_request (radio_female, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_female), radio_male_group);
  radio_male_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_female));

  button_delete = gtk_button_new ();
  gtk_widget_show (button_delete);
  gtk_fixed_put (GTK_FIXED (fixed17), button_delete, 288, 480);
  gtk_widget_set_size_request (button_delete, 74, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button_delete), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image45 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image45);
  gtk_box_pack_start (GTK_BOX (hbox1), image45, FALSE, FALSE, 0);

  label104 = gtk_label_new_with_mnemonic (_("Delete"));
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (hbox1), label104, FALSE, FALSE, 0);

  button_edit = gtk_button_new ();
  gtk_widget_show (button_edit);
  gtk_fixed_put (GTK_FIXED (fixed17), button_edit, 192, 480);
  gtk_widget_set_size_request (button_edit, 74, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_edit), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image46 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image46);
  gtk_box_pack_start (GTK_BOX (hbox2), image46, FALSE, FALSE, 0);

  label105 = gtk_label_new_with_mnemonic (_("Edit"));
  gtk_widget_show (label105);
  gtk_box_pack_start (GTK_BOX (hbox2), label105, FALSE, FALSE, 0);

  button_add = gtk_button_new ();
  gtk_widget_show (button_add);
  gtk_fixed_put (GTK_FIXED (fixed17), button_add, 104, 480);
  gtk_widget_set_size_request (button_add, 74, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_add), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image47 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image47);
  gtk_box_pack_start (GTK_BOX (hbox3), image47, FALSE, FALSE, 0);

  label106 = gtk_label_new_with_mnemonic (_("Add"));
  gtk_widget_show (label106);
  gtk_box_pack_start (GTK_BOX (hbox3), label106, FALSE, FALSE, 0);

  button_search = gtk_button_new ();
  gtk_widget_show (button_search);
  gtk_fixed_put (GTK_FIXED (fixed17), button_search, 376, 480);
  gtk_widget_set_size_request (button_search, 74, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_search), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image48 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image48);
  gtk_box_pack_start (GTK_BOX (hbox4), image48, FALSE, FALSE, 0);

  label107 = gtk_label_new_with_mnemonic (_("Search"));
  gtk_widget_show (label107);
  gtk_box_pack_start (GTK_BOX (hbox4), label107, FALSE, FALSE, 0);

  ID = gtk_label_new (_("ID"));
  gtk_widget_show (ID);
  gtk_fixed_put (GTK_FIXED (fixed17), ID, 32, 24);
  gtk_widget_set_size_request (ID, 49, 17);

  combo_specialite = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combo_specialite);
  gtk_fixed_put (GTK_FIXED (fixed17), combo_specialite, 136, 208);
  gtk_widget_set_size_request (combo_specialite, 261, 37);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_specialite), _("Fitness"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_specialite), _("Crossfit"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_specialite), _("Yoga"));

  button_view_stats = gtk_button_new ();
  gtk_widget_show (button_view_stats);
  gtk_fixed_put (GTK_FIXED (fixed17), button_view_stats, 464, 480);
  gtk_widget_set_size_request (button_view_stats, 104, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_view_stats), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image49 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image49);
  gtk_box_pack_start (GTK_BOX (hbox5), image49, FALSE, FALSE, 0);

  label108 = gtk_label_new_with_mnemonic (_("View stas"));
  gtk_widget_show (label108);
  gtk_box_pack_start (GTK_BOX (hbox5), label108, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) window_coach, "destroy",
                    G_CALLBACK (on_window_coach_destroy),
                    NULL);
  g_signal_connect ((gpointer) window_coach, "show",
                    G_CALLBACK (on_window_coach_show),
                    NULL);
  g_signal_connect ((gpointer) radio_male, "toggled",
                    G_CALLBACK (on_radio_male_toggled),
                    NULL);
  g_signal_connect ((gpointer) radio_female, "toggled",
                    G_CALLBACK (on_radio_female_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_delete, "clicked",
                    G_CALLBACK (on_button_delete_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_edit, "clicked",
                    G_CALLBACK (on_button_edit_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_add, "clicked",
                    G_CALLBACK (on_button_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_search, "clicked",
                    G_CALLBACK (on_button_search_clicked),
                    NULL);
  g_signal_connect ((gpointer) combo_specialite, "changed",
                    G_CALLBACK (on_combo_specialite_changed),
                    NULL);
  g_signal_connect ((gpointer) button_view_stats, "clicked",
                    G_CALLBACK (on_dashboard_button_coach_stats_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_coach, window_coach, "window_coach");
  GLADE_HOOKUP_OBJECT (window_coach, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (window_coach, label98, "label98");
  GLADE_HOOKUP_OBJECT (window_coach, label99, "label99");
  GLADE_HOOKUP_OBJECT (window_coach, label100, "label100");
  GLADE_HOOKUP_OBJECT (window_coach, label101, "label101");
  GLADE_HOOKUP_OBJECT (window_coach, label102, "label102");
  GLADE_HOOKUP_OBJECT (window_coach, First_name, "First_name");
  GLADE_HOOKUP_OBJECT (window_coach, Last_name, "Last_name");
  GLADE_HOOKUP_OBJECT (window_coach, label103, "label103");
  GLADE_HOOKUP_OBJECT (window_coach, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (window_coach, entry_first_name, "entry_first_name");
  GLADE_HOOKUP_OBJECT (window_coach, entry_last_name, "entry_last_name");
  GLADE_HOOKUP_OBJECT (window_coach, spin_age, "spin_age");
  GLADE_HOOKUP_OBJECT (window_coach, entry_phone, "entry_phone");
  GLADE_HOOKUP_OBJECT (window_coach, entry_email, "entry_email");
  GLADE_HOOKUP_OBJECT (window_coach, entry_dispo, "entry_dispo");
  GLADE_HOOKUP_OBJECT (window_coach, label_message, "label_message");
  GLADE_HOOKUP_OBJECT (window_coach, radio_male, "radio_male");
  GLADE_HOOKUP_OBJECT (window_coach, radio_female, "radio_female");
  GLADE_HOOKUP_OBJECT (window_coach, button_delete, "button_delete");
  GLADE_HOOKUP_OBJECT (window_coach, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window_coach, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window_coach, image45, "image45");
  GLADE_HOOKUP_OBJECT (window_coach, label104, "label104");
  GLADE_HOOKUP_OBJECT (window_coach, button_edit, "button_edit");
  GLADE_HOOKUP_OBJECT (window_coach, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window_coach, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window_coach, image46, "image46");
  GLADE_HOOKUP_OBJECT (window_coach, label105, "label105");
  GLADE_HOOKUP_OBJECT (window_coach, button_add, "button_add");
  GLADE_HOOKUP_OBJECT (window_coach, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window_coach, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window_coach, image47, "image47");
  GLADE_HOOKUP_OBJECT (window_coach, label106, "label106");
  GLADE_HOOKUP_OBJECT (window_coach, button_search, "button_search");
  GLADE_HOOKUP_OBJECT (window_coach, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window_coach, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window_coach, image48, "image48");
  GLADE_HOOKUP_OBJECT (window_coach, label107, "label107");
  GLADE_HOOKUP_OBJECT (window_coach, ID, "ID");
  GLADE_HOOKUP_OBJECT (window_coach, combo_specialite, "combo_specialite");
  GLADE_HOOKUP_OBJECT (window_coach, button_view_stats, "button_view_stats");
  GLADE_HOOKUP_OBJECT (window_coach, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window_coach, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window_coach, image49, "image49");
  GLADE_HOOKUP_OBJECT (window_coach, label108, "label108");

  return window_coach;
}

GtkWidget*
create_window_stats (void)
{
  GtkWidget *window_stats;
  GtkWidget *fixed18;
  GtkWidget *label_nb_coachs;
  GtkWidget *textview17;
  GtkWidget *label_nb_moyen;
  GtkWidget *textview19;

  window_stats = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_stats), _("Coach stats"));

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (window_stats), fixed18);

  label_nb_coachs = gtk_text_view_new ();
  gtk_widget_show (label_nb_coachs);
  gtk_fixed_put (GTK_FIXED (fixed18), label_nb_coachs, 64, 128);
  gtk_widget_set_size_request (label_nb_coachs, 168, 48);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (label_nb_coachs)), _("Number of coachs:"), -1);

  textview17 = gtk_text_view_new ();
  gtk_widget_show (textview17);
  gtk_fixed_put (GTK_FIXED (fixed18), textview17, 248, 128);
  gtk_widget_set_size_request (textview17, 144, 48);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview17)), _("4"), -1);

  label_nb_moyen = gtk_text_view_new ();
  gtk_widget_show (label_nb_moyen);
  gtk_fixed_put (GTK_FIXED (fixed18), label_nb_moyen, 64, 200);
  gtk_widget_set_size_request (label_nb_moyen, 168, 56);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (label_nb_moyen)), _("Average age:"), -1);

  textview19 = gtk_text_view_new ();
  gtk_widget_show (textview19);
  gtk_fixed_put (GTK_FIXED (fixed18), textview19, 248, 200);
  gtk_widget_set_size_request (textview19, 144, 56);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview19)), _("25.00"), -1);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_stats, window_stats, "window_stats");
  GLADE_HOOKUP_OBJECT (window_stats, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (window_stats, label_nb_coachs, "label_nb_coachs");
  GLADE_HOOKUP_OBJECT (window_stats, textview17, "textview17");
  GLADE_HOOKUP_OBJECT (window_stats, label_nb_moyen, "label_nb_moyen");
  GLADE_HOOKUP_OBJECT (window_stats, textview19, "textview19");

  return window_stats;
}

