/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *connexion;
  GtkWidget *Espace_Admin;
  GtkWidget *Espace_Coach;
  GtkWidget *Espace_inscription;
  GtkWidget *Gym_Classes;
  GtkWidget *Coach_Management;
  GtkWidget *Member_Management;
  GtkWidget *private_coach_request;
  GtkWidget *join_course;
  GtkWidget *Gym_classes_stats;
  GtkWidget *Coach_stats;
  GtkWidget *Member_stats;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  connexion = create_connexion ();
  gtk_widget_show (connexion);
  Espace_Admin = create_Espace_Admin ();
  gtk_widget_show (Espace_Admin);
  Espace_Coach = create_Espace_Coach ();
  gtk_widget_show (Espace_Coach);
  Espace_inscription = create_Espace_inscription ();
  gtk_widget_show (Espace_inscription);
  Gym_Classes = create_Gym_Classes ();
  gtk_widget_show (Gym_Classes);
  Coach_Management = create_Coach_Management ();
  gtk_widget_show (Coach_Management);
  Member_Management = create_Member_Management ();
  gtk_widget_show (Member_Management);
  private_coach_request = create_private_coach_request ();
  gtk_widget_show (private_coach_request);
  join_course = create_join_course ();
  gtk_widget_show (join_course);
  Gym_classes_stats = create_Gym_classes_stats ();
  gtk_widget_show (Gym_classes_stats);
  Coach_stats = create_Coach_stats ();
  gtk_widget_show (Coach_stats);
  Member_stats = create_Member_stats ();
  gtk_widget_show (Member_stats);

  gtk_main ();
  return 0;
}

