/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_connexion (void);
GtkWidget* create_Espace_Admin (void);
GtkWidget* create_Espace_Coach (void);
GtkWidget* create_Espace_inscription (void);
GtkWidget* create_Gym_Classes (void);
GtkWidget* create_Coach_Management (void);
GtkWidget* create_Member_Management (void);
GtkWidget* create_private_coach_request (void);
GtkWidget* create_join_course (void);
GtkWidget* create_Gym_classes_stats (void);
GtkWidget* create_Coach_stats (void);
GtkWidget* create_Member_stats (void);
